import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import NavbarComponent from "@/app/components/commonComponents/navbarComponent/NavbarComponent";
import FooterComponent from "@/app/components/commonComponents/footerComponent/FooterComponent";
import ScrollToTop from "@/app/components/commonComponents/scrollToTopComponent/ScrollToTopComponent";
import ScrollIndicator from "@/app/components/commonComponents/scrollIndicatorComponent/ScrollIndicatorComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = "light";

  return (
    <html lang="en" className={theme}>
      <body>
        <Providers>
          <ScrollIndicator />
          <NavbarComponent />
          <ScrollToTop />
          {children}
          <FooterComponent />
        </Providers>
      </body>
    </html>
  );
}
